services:
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - 1521:1521
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
    volumes:
      - oracle-data:/u01/app/oracle

volumes:
  oracle-data:
    driver: local
